name: Pre-Merge Checks

on:
  push:
    branches:
      - develop
      - releases/*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch: # run on request (no need for PR)
  workflow_call:  # run by other workflow

# Declare default permissions as read only.
permissions: read-all

jobs:
  Code-Quality-Checks:
    # This is what will cancel the job concurrency
    concurrency:
      group: ${{ github.workflow }}-Linting-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.10"
      - name: Install tox
        run: python -m pip install tox==4.4.6
      - name: Code quality checks
        run: tox -vv -e pre-commit

  Unit-Test:
    runs-on: ubuntu-22.04
    needs: Code-Quality-Checks
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            tox-env: "py310"
          - python-version: "3.11.8"
            tox-env: "py311"
    name: Unit-Test-${{ matrix.tox-env }}
    # This is what will cancel the job concurrency
    concurrency:
      group: ${{ github.workflow }}-Unit-${{ github.event.pull_request.number || github.ref }}-${{ matrix.tox-env }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: python -m pip install tox==4.4.6
      - name: Run unit test
        env:
          XDG_CACHE_HOME: /home/cibot/data
        run: tox -vv -e dev-${{ matrix.tox-env }} -- tests/unit --csv=.tox/dev-${{ matrix.tox-env }}/unit-test.csv
          --cov=openvino_xai --cov-report term --cov-report xml:.tox/dev-${{ matrix.tox-env }}/unit-test-coverage.xml
      - name: Upload artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: unit-test-results-${{ matrix.tox-env }}
          path: |
            .tox/dev-${{ matrix.tox-env }}/*.csv
            .tox/dev-${{ matrix.tox-env }}/*.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: .tox/dev-${{ matrix.tox-env }}/unit-test-coverage.xml
          flags: dev-${{ matrix.tox-env }}

  Integration-Test:
    runs-on: ubuntu-22.04
    needs: Unit-Test
    # This is what will cancel the job concurrency
    concurrency:
      group: ${{ github.workflow }}-Integration-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.10"
      - name: Install tox
        run: python -m pip install tox==4.4.6
      - name: Run Integration Test
        run: tox -vv -e val-py310 -- tests/intg --csv=.tox/dev-py310/intg-test.csv -n 1 --clear-cache
      - name: Upload artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: intg-test-results
          path: .tox/dev-py310/*.csv
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
